# filepath: config/training/default.yaml
batch_size: 64 # how many independent sequences will we process in parallel?
block_size: 256 # what is the maximum context length for predictions?
learning_rate: 0.0003
max_iters: 5000
eval_interval: 500
eval_iters: 200
device: 'cuda' # or 'cpu'
torch_seed: 1337
log_dir: logs